pipeline {
    agent any
    stages {

        stage('Build') {
            steps {
                echo "Build"
                bat """
                msbuild /t:Build /p:Configuration=Debug
                """
            }
        }
        stage('Test') {
            steps {
                echo "Test"
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploy"
            }
        }
    }
}
